language: c
dist: trusty
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - aspcud
    - opam
install:
  - opam init --yes
  - opam update --yes
  - travis_wait 30 opam switch --yes $OCAML_VERSION
  - eval `opam config env`
  - opam switch
  - opam pin add --yes --no-action General --dev-repo
  - opam pin add --yes --no-action JsOfOCairo --dev-repo
  - opam install --yes JsOfOCairo General cairo2 jbuilder menhir
  - opam upgrade --yes
  - opam list
script:
  - jbuilder runtest
env:
  - OCAML_VERSION=4.02.3
  - OCAML_VERSION=4.06.0
  - OCAML_VERSION=4.06.0+flambda
cache:
  directories:
  - $HOME/.opam
