language: c
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - aspcud
install:
  - wget --output-document=$HOME/opam2 https://github.com/ocaml/opam/releases/download/2.0.1/opam-2.0.1-x86_64-linux
  - chmod +x $HOME/opam2
  - test -d $HOME/.opam/repo || $HOME/opam2 init --yes --disable-sandboxing
  - $HOME/opam2 update --yes
  - test -d $HOME/.opam/$OCAML_VERSION || $HOME/opam2 switch create --yes $OCAML_VERSION
  - eval `$HOME/opam2 config env`
  - $HOME/opam2 switch list
  - $HOME/opam2 pin add --yes --no-action General --dev-repo
# - $HOME/opam2 pin add --yes --no-action JsOfOCairo --dev-repo
  - $HOME/opam2 install --yes JsOfOCairo General cairo2 dune menhir
  - $HOME/opam2 upgrade --yes
  - $HOME/opam2 install --yes cairo2=0.5
  - $HOME/opam2 list
script:
  - dune runtest
env:
  - OCAML_VERSION=4.02.3
  - OCAML_VERSION=4.06.0
  - OCAML_VERSION=4.06.0+flambda
cache:
  directories:
  - $HOME/.opam
